server:
  port: 8080
wechat:
  # sgj.proxy.jingxiantech.com:  改成自己的域名，还有static/preorder.html里面102行
  notifyurl: http://sgj.proxy.jingxiantech.com/pay/paidNotify
pooul:
  pay:
    url: https://api-uat.pooul.com/v2/pay?merchant_id={0}
    preOrder: https://api-uat.pooul.com/v2/pay/pre_order?merchant_id={0}
    publickey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+Vd3j0McNfR3VvT7mZp/7M6ULFJSc3dh3/56JP8DZk+cDlXC2LR0z0OELJeyTitFeBjpPWzWH3OOFI/OL3nD5/oNZfK+wHd4Tzxj2SdWlyuqRhNv3xG2obUUYZ9urUvkCvxL1SclaXW7cq22V/TTNSgJq7CGdc+q/XLNqcmLt7QIDAQAB"
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml